
trigger:
  branches:
    include:
    - master
    - feature-*
    # - dev
    # - stage
    # - prod
       
pool: AWS-agents
#   vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Installing terrafor by mergeing & testing m"
            displayName: Terraform - Install
            
          - script: echo "initializing terraform by mergeing & testing "
            displayName: Terraform - Init
            
          - script: echo "validating terraform by mergeing & testing "
            displayName: Terraform - Validate
            
          - script: |
              echo "planning terraform by merging & testing" >> terraformtest.txt
              ls -la
              cat terraformtest.txt
            displayName: Terraform - Plan

          - task: CopyFiles@2
            displayName: 'artifacts: copy tf files'
            inputs:
              Contents: '$(System.DefaultWorkingDirectory)/**/?(*.txt|*.plan|*.sh)'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
          - publish: $(Build.ArtifactStagingDirectory)/
            artifact: tf
            displayName: 'artifacts: upload tf'

  - template: deploy.yaml
    parameters:
      dependsOn: Build
      environmentName: test
      deployBranch: master
      terraformVersion: "testv1"
  
  - template: deploy.yaml
    parameters:
      dependsOn: test
      environmentName: dev
      deployBranch: master
      terraformVersion: "devv1"
  
  - template: deploy.yaml
    parameters:
      dependsOn: dev
      environmentName: stage
      deployBranch: master
      terraformVersion: "stagev1"
