# Repo: YourRepo/YourProject
# File: azure-pipelines.yml
# trigger:
#   - prod
#   - stage
#   - develop
#   - feature-*
#   - DEVOPS-*
  
resources:
  repositories:
    - repository: templates
      type: github
      name: Adityad92/azure-pipeline-utility
      endpoint: Adityad92

variables:
- group: dxfarm-variable-group
- name: vmImageName
  value: 'AWS-agents'

stages:
- template: my_template.yaml@templates
