variables:
  vmImageName: "ubuntu-latest" # Agent VM image name

# trigger:
#   - production
#   - pull_request

stages:
- ${{ if or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'PullRequest')) }}:
  - stage: Test
    displayName: Test stage
    jobs:
      - job: Test
        displayName: Test job
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              echo "Testing ..."
            displayName: 'Test job script'
            
  - stage: semgrep
    displayName: Semgrep Security Scan
    jobs:
      - job: semgrep
        displayName: Run Semgrep Security Scan
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              python -m pip install --upgrade pip
              pip install semgrep
              semgrep ci
            env:
              SEMGREP_RULES: p/default
            displayName: 'Semgrep security scan'
            
- ${{ if and(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build job
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              echo "Building ..."
            displayName: 'Build job script'
            
  - stage: Deploy
    displayName: Deploy to Dev
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy to AKS
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              echo "Deploying ..."
            displayName: 'Deploy job script'
