# Repo: YourRepo/YourProject
# File: azure-pipelines.yml
# trigger:
#   - prod
#   - stage
#   - develop
#   - feature-*
#   - DEVOPS-*
  
resources:
  repositories:
    - repository: templates
      type: github
      name: Adityad92/azure-pipeline-utility
      endpoint: Adityad92

jobs:
- template: my_template.yaml@templates
