
trigger:
  branches:
    include:
    - dev
    - stage
    - prod
       
pool: AWS-agents
#   vmImage: "ubuntu-latest"


stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Installing terraform"
            displayName: Terraform - Install
            
          - script: echo "initializing terraform"
            displayName: Terraform - Init
            
          - script: echo "validating terraform"
            displayName: Terraform - Validate
            
          - script: echo "planning terraform"
            displayName: Terraform - Plan

          - script: echo "applying terraform"
            displayName: Terraform - Apply

