pool: AWS-agents

# trigger:
#   - production
#   - pull_request

  - stage: Test
    displayName: Test stage
    jobs:
      - job: Test
        displayName: Test job
        steps:
          - script: |
              cat .npmrc
            displayName: 'Test job script'