trigger:
  - develop
  - integration
  - main
  - feature-*
  - DEVOPS-*

resources:
  repositories:
    - repository: templates
      type: github
      name: Adityad92/azure-pipeline-utility
      endpoint: Adityad92

variables:
- group: dxfarm-variable-group
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- template: my_template.yaml@templates
