# Repo: Contoso/LinuxProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: Adityad92/azure-pipeline-utility

jobs:
- template: my_template.yaml@templates  # Template reference
