# Repo: YourRepo/YourProject
# File: azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      type: github
      name: Adityad92/azure-pipeline-utility
      # ref: refs/heads/main  # Specify the branch or tag of the template repository

jobs:
- template: my_template.yaml@templates  # Template reference
