# trigger:
#   - develop
#   - integration
#   - main
#   - feature-*
#   - DEVOPS-*

trigger:
  branches:
    include:
      - develop
      - integration
      - main
      - feature-*
      
resources:
  repositories:
    - repository: templates
      type: github
      name: Adityad92/azure-pipeline-utility
      endpoint: Adityad92
      # ref: refs/tags/v1.0 # optional ref to pin to

variables:
- group: dxfarm-variable-group
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- template: my_template.yaml@templates
