# pool: AWS-agents

variables:
- group: my-variable-group

steps:
  - script: |
      # # sed -i "s/NPM_REGISTRY/$(NPM_REGISTRY)/g" .npmrc
      # echo //npm.pkg.github.com/:_authToken=$(NPM_REGISTRY) >> .npmrc
      # cat .npmrc
      # # sed -i "s/NPM_REGISTRY/$(NPM_REGISTRY)/g" token.conf
      # # cat token.conf
      top -b -n 1 -o %MEM
    displayName: 'Test job script'

  # - script: |
  #     # python -m pip install --upgrade pip
  #     # pip install semgrep
  #     semgrep ci
  #   env:
  #     SEMGREP_RULES: p/default
  #   displayName: 'Semgrep security scan'