variables:
  vmImageName: "ubuntu-latest"

# trigger:
#   - delete

trigger:
  branches:
    include:
    - delete

stages:        
  - stage: test
    displayName: test branch
    jobs:
      - job: test
        displayName: test branch
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              echo "this is the branch ${{variables['Build.SourceBranchName']}}"
            displayName: 'test branch'
            
