variables:
  vmImageName: "ubuntu-latest"

stages:
  - stage: BuildDev
    displayName: Build Dev
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    jobs:
      - job: BuildJobDev
        displayName: Build Dev Job
        pool:
          vmImage: $(vmImageName)
        steps:
#           - checkout: self
#             persistCredentials: true
          - script: echo "Building Dev"
            displayName: 'Build Dev job script'

  - stage: DeployDev
    displayName: Deploy to Dev
    dependsOn: BuildDev
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    jobs:
      - job: DeployJobDev
        displayName: Deploy to Dev
        pool:
          vmImage: $(vmImageName)
        steps:
#           - checkout: self
#             persistCredentials: true
          - script: echo "Deploying Dev"
            displayName: 'Deploy Dev job script'

  - stage: BuildProd
    displayName: Build Prod
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/prod')
    jobs:
      - job: BuildJobProd
        displayName: Build Prod Job
        pool:
          vmImage: $(vmImageName)
        steps:
#           - checkout: self
#             persistCredentials: true
          - script: echo "Building Prod"
            displayName: 'Build Prod job script'

  - stage: DeployProd
    displayName: Deploy to Prod
    dependsOn: BuildProd
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/prod')
    jobs:
      - job: DeployJobProd
        displayName: Deploy to Prod
        pool:
          vmImage: $(vmImageName)
        steps:
#           - checkout: self
#             persistCredentials: true
          - script: echo "Deploying Prod"
            displayName: 'Deploy Prod job script'
