
trigger:
  branches:
    include:
    - dev
    - stage
    - prod
       
pool: AWS-agents
#   vmImage: "ubuntu-latest"


stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Installing terrafor by mergeing & testing m"
            displayName: Terraform - Install
            
          - script: echo "initializing terraform by mergeing & testing "
            displayName: Terraform - Init
            
          - script: echo "validating terraform by mergeing & testing "
            displayName: Terraform - Validate
            
          - script: echo "planning terraform by mergeing & testing "
            displayName: Terraform - Plan

          - script: echo "applying terraform by mergeing & testing "
            displayName: Terraform - Apply

